name: tr-dns

networks:
  net_t2:
    name: net_t2
    external: true

  socket_proxy:
    name: socket_proxy
    external: true

  net_db:
    name: net_db
    external: true

  net_redis:
    name: net_redis
    external: true

########################### SECRETS

secrets:
  #traefik
  htpasswd:
    file: $DOCKERDIR/secrets/htpasswd
  cf_email:
    file: $DOCKERDIR/secrets/cf/cf_email
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf/cf_dns_api_token
  cf_token:
    file: $DOCKERDIR/secrets/cf/cf_token
  #authelia
  authelia_jwt_secret:
    file: $DOCKERDIR/secrets/authelia/jwt_secret
  authelia_session_secret:
    file: $DOCKERDIR/secrets/authelia/session_secret
  authelia_storage_mysql_password:
    file: $DOCKERDIR/secrets/authelia/storage_mysql_password
  authelia_storage_encryption_key:
    file: $DOCKERDIR/secrets/authelia/storage_encryption_key
  #db
  mysql_root_password:
    file: $DOCKERDIR/secrets/db/mysql_root_password
  #redis
  vaultwarden_admin_token:
    file: $DOCKERDIR/secrets/vl/vaultwarden_admin_token
include:
  # core
  - compose/traefik.yml
  - compose/socket-proxy.yml
  - compose/portainer.yml
  # db
  - compose/mariadb.yml
  - compose/redis.yml
  - compose/influxdb.yml
  # monitoring
  - compose/uptime-kuma.yml
  #- compose/glances.yml
  # auth
  - compose/authelia.yml
  # src
  - compose/phpmyadmin.yml
  # apps
  #- compose/it-tools.yml
  #- compose/owncloud.yml
  - compose/vaultwarden.yml
  - compose/dozzle.yml
  #- compose/filebr.yml
  - compose/whats-up-docker.yml
  # crowdsec
  - compose/crowdsec.yml
  #- compose/crowdsec-db.yml
  # adguard
  - compose/traefik-certs-dumper.yml
  - compose/adquard.yml
volumes:
  #
  portainer_data: {}
  #
  kuma-data: {}
  influxdb_data: {}
  #
  authelia_data: {}
  #
  redis_data: {}
  mariadb_data: {}
  #
  owncloud_files: {}
  #
  crowdsec_data: {}
  #
  vaultwarden: {}
  #
  adquard: {}
  #
  filebrowser_data: {}
  #
  whats-up-docker: {}