CREATE USER 'authelia' @'%' IDENTIFIED BY '0fedda25de6c584e330abf6955a4c1d0';
GRANT USAGE ON *.* TO 'authelia' @'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `authelia`;
GRANT ALL PRIVILEGES ON `authelia`.* TO 'authelia' @'%';
--###
CREATE USER 'owncloud' @'%' IDENTIFIED BY '59118055286004b1e20ac5e9b9668bb4aa';
GRANT USAGE ON *.* TO 'owncloud' @'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `owncloud`;
GRANT ALL PRIVILEGES ON `owncloud`.* TO 'owncloud' @'%';