services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    security_opt: [no-new-privileges:true]
    restart: always
    profiles: ["adguard", "all"]
    networks:
      net_t2:
        ipv4_address: 172.16.90.253
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp"   # DHCP (if needed)
      # - "853:853/tcp" # DNS-over-TLS
    volumes:
      - adguard:/opt/adguardhome/work
      - ${APPDIR}/adguard/conf:/opt/adguardhome/conf
      # Certificates from traefik-certs-dumper
      - ${CERTDIR}/shared/certs/${DOMAINNAME}:/certs:ro
    environment:
      - TZ=${TZ}
    labels:
      traefik.enable: true
      traefik.http.routers.adguard-rtr.entrypoints: https
      traefik.http.routers.adguard-rtr.rule: Host(`adguard.${DOMAINNAME}`)
      traefik.http.routers.adguard-rtr.service: adguard-svc
      traefik.http.services.adguard-svc.loadbalancer.server.port: 80
      # traefik.http.routers.adguard-rtr.middlewares: authelia@file