services:
  # crowdsec
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    expose:
      - 6060
      - 8080
    environment:
      TZ: $TZ
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux LePresidente/authelia"
      PARSERS: "crowdsecurity/dateparse-enrich crowdsecurity/traefik-logs crowdsecurity/sshd-logs crowdsecurity/syslog-logs crowdsecurity/geoip-enrich LePresidente/authelia-logs"
      GID: "${GID-1000}"
      CUSTOM_HOSTNAME: docker-crowdsec
    volumes:
      #ro
      - $DOCKERDIR/logs:/logs:ro
      - /var/log:/var/log:ro
      # wr
      - $APPDIR/crowdsec:/etc/crowdsec
      - crowdsec_data:/var/lib/crowdsec/data
    networks: [net_t2]
    # if use local
    # networks:
    #   net_t2:
    #     ipv4_address: 172.16.90.253
    profiles: ["crowdsec", "all"]
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
#    labels:
#      traefik.enable: true
#      traefik.http.routers.crowdsec-rtr.entrypoints: https
#      traefik.http.routers.crowdsec-rtr.rule: Host(`$CROWDSEC_DOMAINNAME`)
#      traefik.http.routers.crowdsec-rtr.service: crowdsec-svc
#      traefik.http.services.crowdsec-svc.loadbalancer.server.port: 8080
#      traefik.http.routers.crowdsec-rtr.tls: true
