services:
  influxdb:
    container_name: influxdb
    image: influxdb:2-alpine
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    profiles: ["database", "all"]
    networks: [net_t2, net_db]
    secrets:
      - influxdb_password
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - TZ=${TZ}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influxdb_password
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
    labels:
      traefik.enable: true
      traefik.http.routers.influx-rtr.entrypoints: https
      traefik.http.routers.influx-rtr.rule: Host(`influx.${DOMAINNAME}`)
      traefik.http.routers.influx-rtr.service: influx-svc
      traefik.http.services.influx-svc.loadbalancer.server.port: 8086
      # traefik.http.routers.influx-rtr.middlewares: chain-internal@file
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3