services:
  # InfluxDB - Database for sensor data
  influxdb:
    image: influxdb
    container_name: influxdb
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    profiles: ["db", "all"]
    networks: [net_t2]
    volumes:
      - $DOCKERDIR/appdata/influxdb2/config:/etc/influxdb2
      - influxdb_data:/var/lib/influxdb2
    labels:
      traefik.enable: true
      traefik.http.routers.influxdb-rtr.entrypoints: https
      traefik.http.routers.influxdb-rtr.rule: Host(`$INF_DOMAINNAME`)
      traefik.http.routers.influxdb-rtr.service: influxdb-svc
      traefik.http.services.influxdb-svc.loadbalancer.server.port: 8086
      #traefik.http.routers.influxdb-rtr.middlewares: middlewares-authelia@file
      traefik.http.routers.influxdb-rtr.tls: true
