services:
  # mariadb
  mariadb:
    container_name: mariadb
    image: "bitnami/mariadb:latest"
    restart: unless-stopped
    expose:
      - 3306
    volumes:
      - mariadb_data:/bitnami/mariadb/data
      - /etc/localtime:/etc/localtime:ro
    secrets: [mysql_root_password]
    security_opt: [no-new-privileges:true]
    networks: [net_db]
    profiles: ["db", "all"]
    environment:
      PUID: $PUID
      PGID: $PGID
      ALLOW_EMPTY_PASSWORD: no
      MARIADB_SKIP_TEST_DB: yes
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
