services:
  # owncloud keeping secrets 
  owncloud:
    image: owncloud/server
    container_name: owncloud
    restart: always
    networks: [net_t2, net_db, net_redis]
    profiles: ["apps", "all"]
    security_opt: [no-new-privileges:true]
    environment:
      TZ: $TZ
      OWNCLOUD_DOMAIN: ${OWN_DOMAINNAME}
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: owncloud
      OWNCLOUD_DB_USERNAME: owncloud
      OWNCLOUD_DB_PASSWORD: 591180552asdasd86004b1e20ac5e9b9668bb4aa
      OWNCLOUD_DB_HOST: mariadb
      OWNCLOUD_ADMIN_USERNAME: addmin
      OWNCLOUD_ADMIN_PASSWORD: db641c9e5dgdfg43gde2ddd497a5684e8750ffcc7ef7
      OWNCLOUD_MYSQL_UTF8MB4: true
      OWNCLOUD_REDIS_ENABLED: true
      OWNCLOUD_REDIS_HOST: redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - owncloud_files:/mnt/data
    labels:
      traefik.enable: true
      traefik.http.routers.owncloud-rtr.entrypoints: https
      traefik.http.routers.owncloud-rtr.rule: Host(`$OWN_DOMAINNAME`)
      traefik.http.routers.owncloud-rtr.service: owncloud-svc
      traefik.http.services.owncloud-svc.loadbalancer.server.port: 8080
      traefik.http.routers.owncloud-rtr.tls: true
