services:
  # phpMyAdmin - Database management
  # Create a new user with admin privileges. Cannot login as MySQL root for some reason.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    profiles: ["src", "all"]
    networks: [net_t2, net_db]
    environment:
      - PMA_HOST=$DB_HOST
      - PMA_PORT=$DB_PORT
      #- PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    secrets: [mysql_root_password]
    labels:
      traefik.enable: true
      traefik.http.routers.phpmy-rtr.entrypoints: https
      traefik.http.routers.phpmy-rtr.rule: Host(`$PMA_DOMAINNAME`)
      traefik.http.routers.phpmy-rtr.service: phpmy-svc
      traefik.http.services.phpmy-svc.loadbalancer.server.port: 80
      #traefik.http.routers.phpmy-rtr.middlewares: middlewares-authelia@file
      traefik.http.routers.phpmy-rtr.tls: true
