services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H tcp://socket-proxy:2375
    security_opt:
      - no-new-privileges:true
    read_only: true
    profiles:
      - core
      - all
    restart: unless-stopped
    networks:
      - net_t2
      - socket_proxy
    volumes:
      - portainer_data:/data
    environment:
      - TZ=$TZ
    labels:
      traefik.enable: true
      traefik.http.routers.portainer-rtr.entrypoints: https
      traefik.http.routers.portainer-rtr.rule: Host(`portainer.${DOMAINNAME}`)
      traefik.http.routers.portainer-rtr.service: portainer-svc
      traefik.http.services.portainer-svc.loadbalancer.server.port: 9000
      traefik.http.routers.portainer-rtr.middlewares: local-ip@file