services:
  # Redis - Key-value Store
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    expose:
      - 6379
    networks: [net_redis]
    security_opt: [no-new-privileges:true]
    profiles: ["db", "all"]
    volumes:
      - redis_data:/data
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
