services:
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    security_opt:
      - no-new-privileges:true
    restart: always
    profiles:
      - core
      - all
    networks:
      socket_proxy: null
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LOG_LEVEL=info
      - CONTAINERS=1
      - IMAGES=1
      - EVENTS=1
      - NETWORKS=1
      - SERVICES=1
      - TASKS=1
      - INFO=1
      - VERSION=1
      - POST=1
      - VOLUMES=1
      - EXEC=1
      - SYSTEM=1
      - BUILD=1
      - AUTH=0
      - COMMIT=0
      - CONFIGS=0
      - DISTRIBUTION=0
      - GRPC=0
      - NODES=0
      - PLUGINS=0
      - SECRETS=0
      - SESSION=0
      - SWARM=0
      - DISABLE_IPV6=1
    healthcheck:
      test:
        - CMD-SHELL
        - pidof haproxy || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
