services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    networks: [net_t2]
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    profiles: ["apps", "all"]
    #ports:
    #  - "8384:8384"
    #  - "22000:22000/tcp"
    #  - "22000:22000/udp"
    #  - "21027:21027/udp"
    volumes:
      - $DOCKERDIR:/data
      - $APPDIR/syncthing:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      traefik.enable: true
      traefik.http.routers.sync-rtr.entrypoints: https
      traefik.http.routers.sync-rtr.rule: Host(`$SYNC_DOMAINNAME`)
      traefik.http.routers.sync-rtr.service: sync-svc
      traefik.http.services.sync-svc.loadbalancer.server.port: 8384
      #traefik.http.routers.sync-rtr.middlewares: middlewares-authelia@file
      traefik.http.routers.sync-rtr.tls: true
      traefik.http.routers.sync-rtr.tls.options: tls-opts@file