services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    profiles:
      - core
      - all
    security_opt:
      - no-new-privileges:true
    networks:
      net_t2: null
      socket_proxy: null
    depends_on:
      socket-proxy:
        condition: service_healthy
    ports:
      - '80:80'
      - '443:443'
    environment:
      - TZ=${TZ}
      - DOMAINNAME=${DOMAINNAME}
      - ACME_EMAIL=${ACME_EMAIL}
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
    secrets:
      - htpasswd
      - cf_dns_api_token
      - traefik_influx_token
    volumes:
      - ${APPDIR}/traefik/traefik.yml:/traefik.yml:ro
      - ${APPDIR}/traefik/rules:/etc/traefik/rules:ro
      - ${APPDIR}/traefik/acme.json:/acme.json
      - ${LOGDIR}/traefik:/logs
      - ${DOCKERDIR}/certs:/certs:ro
    healthcheck:
      test:
        - CMD
        - traefik
        - healthcheck
        - '--ping'
        - '--port'
        - '8082'
      interval: 30s
      timeout: 10s
      retries: 3
