services:
  #uptime-kuma
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    security_opt: [no-new-privileges:true]
    restart: always
    networks: [net_t2, socket_proxy]
    profiles: ["monitoring", "all"]
    volumes:
      - kuma-data:/app/data
    labels:
      traefik.enable: true
      traefik.http.routers.kuma-rtr.entrypoints: https
      traefik.http.routers.kuma-rtr.rule: Host(`$KUMA_DOMAINNAME`)
      traefik.http.routers.kuma-rtr.service: kuma-svc
      traefik.http.services.kuma-svc.loadbalancer.server.port: 3001
      #traefik.http.routers.kuma-rtr.middlewares: middlewares-authelia@file
      traefik.http.routers.kuma-rtr.tls: true
