services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    volumes:
      - vaultwarden:/data
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"
      # echo -n "ADMIN_TOKEN_FILE" | argon2 "$(openssl rand -base64 32)" -e -id -k 65540 -t 3 -p 4
      #ADMIN_TOKEN_FILE: /run/secrets/vaultwarden_admin_token
    networks: [net_t2]
    secrets: [vaultwarden_admin_token]
    profiles: ["apps", "all"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      traefik.enable: true
      traefik.http.routers.vltwrn-rtr.entrypoints: https
      traefik.http.routers.vltwrn-rtr.rule: Host(`$VLTWRN_DOMAINNAME`)
      traefik.http.routers.vltwrn-rtr.service: vltwrn-svc
      traefik.http.services.vltwrn-svc.loadbalancer.server.port: 80
      traefik.http.routers.vltwrn-rtr.tls: true
      traefik.http.routers.vltwrn-rtr.tls.options: tls-opts@file
