services:
  # whoami
  whoami:
    image: containous/whoami
    container_name: whoami
    networks: [net_t2]
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    profiles: ["test", "all"]
    command:
      - --port=8082
    labels:
      traefik.enable: true
      traefik.http.routers.whoami-rtr.entrypoints: https
      traefik.http.routers.whoami-rtr.rule: Host(`$WHOAMI_DOMAINNAME`)
      traefik.http.routers.whoami-rtr.service: whoami-svc
      traefik.http.services.whoami-svc.loadbalancer.server.port: 8082
      #traefik.http.routers.whoami-rtr.middlewares: middlewares-authelia@file
      traefik.http.routers.whoami-rtr.tls: true
      traefik.http.routers.whoami-rtr.tls.options: tls-opts@file